# Generated by Django 4.2.1 on 2023-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConvertedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("youtube_url", models.URLField()),
                ("conversion_type", models.CharField(max_length=10)),
                (
                    "file_path",
                    models.FilePathField(blank=True, path="media/converted_files/"),
                ),
            ],
        ),
    ]
